### ISSUE TITLE
Can't get data

### ISSUE THREAD

**Issue by avinasraj** [PortalGNU/node-sharepoint-rest#4]
What should I put for the "DOMAIN" keyword inside username?
My url is "https://ionit.sharepoint.com/sites/solutions/eIPS"

**Comment by mikekunze** [comment]
Its been many years since I've used sharepoint.  From memory, I believe you dont specify the DOMAIN as it inherits the default domain from sharepoint.  I could be wrong though.  You may need to try a few different combinations.   Please post your findings once you get it working so others may benefit from that knowledge.  Thanks!!
